services:
  viewer:
    container_name: fogofworld-viewer
    build:
      context: .
      args:
        - DOMAIN=${DOMAIN}
        - PORT=${PORT}
    volumes:
      - ./data:/data
    ports:
      - "${PORT}:${PORT}"
    command: ["python", "main.py", "/data"]
