services:
  viewer:
    container_name: fogofworld-viewer
    build:
      context: .
      args:
        - DOMAIN=${DOMAIN}
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    command: ["python", "main.py", "/data"]
